### PR TITLE
Update Supported Sites

### PR DESCRIPTION
**Pull request by comwizz2**
How to be a Werewolf
Undevine

### CODE REVIEW

**Comment by oseparovic** [comment]
Thank you!

**Comment by comwizz2** [comment]
Just buying brownie points for the wife, she loves the app!

**Comment by oseparovic** [comment]
You got some brownie points from me too 👍 Feel free to email us if either of you have any feedback

**Comment by comwizz2** [comment]
No if you need any help hit me up. Webdev by day I can do this stuff in my
sleep :P

**Comment by comwizz2** [comment]
No prob that is

**Pull request merged**
