### PR TITLE
comics cleanup & addition

### PR DESCRIPTION
**Pull request by swapnilsarwe**
* [all gocomics url updated to https](https://github.com/oseparovic/comic_selectors/pull/173/commits/2b1c4440543641075ea6425d034e8be4aa33e823)
* marked "Not Invented Here" as unsuppported - navigation logic moved to JS - unable to use css selector on html content
* [fixes nextSelector & lastSelector for "Three Panel Souls"](https://github.com/oseparovic/comic_selectors/pull/173/commits/438bf22ae09f1c515db195b8e1d43b5d319e6c8d)
* [marking "Erin Dies Alone"" as unsupported - domain parked](https://github.com/oseparovic/comic_selectors/pull/173/commits/d588d1ab6a4eb02d06f7cf6202dd68a44e90783a)  - [whois](https://www.whois.com/whois/dyingalone.net)
* [marking "Thieves Can't" as unsupported - domain parked](https://github.com/oseparovic/comic_selectors/pull/173/commits/d588d1ab6a4eb02d06f7cf6202dd68a44e90783a) - [whois](https://www.whois.com/whois/yesthievescan.com)
* ["Everblue" comic selectors fixed](https://github.com/oseparovic/comic_selectors/pull/173/commits/918f03b2c91622f60180be46fffe54543b9074d2)
* [Bird Boy marked unsupported - website seems to be down](https://github.com/oseparovic/comic_selectors/pull/173/commits/8e58d6822f70dc232f79d7ab21b9cc81b972ac44)
* [Go Get a Roomie - fixes all selectors](https://github.com/oseparovic/comic_selectors/pull/173/commits/1923a9ad046e548bc2ddd20e23d965844dc042ea)
* [witchycomic - selectors fixed and removed random selector](https://github.com/oseparovic/comic_selectors/pull/173/commits/59ec34d2e4efcb3fae7e7d398fcffaaf186f86a5)
* [Johnny, Roy y Steffy - selectors fixed with new selectors](https://github.com/oseparovic/comic_selectors/pull/173/commits/c560dd301b81d772ba48b7029d501fb38efc3586)
* [Buni - imageSelector fix updated](https://github.com/oseparovic/comic_selectors/pull/173/commits/d498366fde84d755cde8b20f75465637ea192c6e)

### CODE REVIEW

**Comment by swapnilsarwe** [comment]
@oseparovic 
are you ok adding all the comics from gocomics.com from the following url
https://www.gocomics.com/comics/a-to-z
in supported_sites.json ?

**Comment by oseparovic** [comment]
> @oseparovic are you ok adding all the comics from gocomics.com from the following url https://www.gocomics.com/comics/a-to-z in supported_sites.json ?

We can definitely add these but this is a huge job unless you script it

One follow-up before we merge. Changing the selector URL to https will prevent users who have these comics in their feed from updating their selectors (unless they remove and re-add them). In my infinite wisdom when I made this app years ago I used the URLs as the IDs so changing the URL will create a new element in their database instead of updating their existing selectors. 

I think this is ok as we have to update these eventually it's just a bummer. If you have suggestions I would love to hear from you

**Comment by swapnilsarwe** [comment]
@oseparovic you know better.

Let us not worry about https changes for now. 
Will create another PR for the same.

So that we at least get fixes updated soon.

Regarding adding all the comics, I guess I can script it without changing any order in current json with only new ones added in the last.

**Comment by oseparovic** [comment]
Sounds good, thank you!

**Pull request merged**
