### PR TITLE
Update supported_sites.json

### PR DESCRIPTION
**Pull request by Narcwis**
Added The Property of Hate

### CODE REVIEW

**Comment by oseparovic** [comment]
thank you!

**Comment by Narcwis** [comment]
You're welcome! Glad I can help. Would I need to update the app or is this list being fetched from a server?

**Comment by oseparovic** [comment]
fetched from server. Should be available already. Just go to add a comic and your new comic will be in the list

**Comment by Narcwis** [comment]
Awesome! I will keep adding comics when I find them :)

**Pull request merged**
