### PR TITLE
Fix 2 giantitp comics

### PR DESCRIPTION
**Pull request by emaas**

### CODE REVIEW

**Comment by oseparovic** [comment]
thank you!

**Comment by emaas** [comment]
It's just a navigation fix tough.
The image selector still doesn't work.
However i don't really know how to test that?

**Comment by oseparovic** [comment]
I fixed the image selector for Order of the Stick. If you kill your app and start it again it should refresh the selector list and then you'll be able to see the images for that comic.

Fixing Erfworld now too

**Comment by oseparovic** [comment]
It seems that Erfworld has been unpublished and I haven't been able to find any other sources. Removed for now

**Comment by emaas** [comment]
Super, thanks!

**Pull request merged**
